cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls'), name='orders'),
    path('cart/', include('cart.urls'), name='cart'),
    path('', include('shop.urls'), name='shop'),
]


if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=1, max_value=21)
    update = forms.BooleanField(required=False,
                                initial=True,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from shop.utils import *
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block css-files %} 
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}" />
{% endblock %}

{% block title %}
  Корзина покупок
{% endblock %}


{% block content %}
  <p class="p">Мій кошик</p>
  {% if cart %}
    <table  class="alingcenter" width="99%">
      <thead>
        <tr class="colortable1">
          <th>Видалити</th>
          <th>Фото</th>
          <th width="20%">Товар</th>
          <th>Обновити кількість</th>
          <!-- <th>Видалити</th> -->
          <th>Кількість</th>
          <th>Ціна за шт</th>
          <th>Загальна сумма</th>
        </tr>
      </thead>
      <tbody class="colortable2">
        {% for item in cart %}
          {% with product=item.product %}
            <tr>
              <td><a class="colora"  href="{% url 'cart:cart_remove' product.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
              <td>
                <a href="{{ product.get_absolute_url }}">
                  <img class="sizeimg" src="{% if product.main_image %}{{ product.main_image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </a>
              </td>
              <td >{{ product.name }}</td>
              <td>
                <form  action="{% url 'cart:cart_add' product.id %}" method="post">
                  <div class="quantity-wrapper">
                    <div class="quantity">
                      {{ item.update_quantity_form.quantity }}
                    </div>
                </div>
                  {{ item.update_quantity_form.update }}
                  <input type="submit" value="Обновити">
                  {% csrf_token %}
                </form>
              </td>
              <!-- <td><a class="colora"  href="{% url 'cart:cart_remove' product.id %}">Видалити</a></td> -->
              <td >
                {{ item.quantity }}
              </td>
              <td >{{ item.price }}грн.</td>
              <td >{{ item.total_price }}грн.</td>
            </tr>
          {% endwith %}
        {% endfor %}
      </tbody>
    </table>
    <p class="text-right">
      <td >{{ cart.get_total_price }}грн.</td>
      <a class="colorhref" href="{% url 'order_create' %}" class="button">Оформити замовлення</a>
    </p>
    <hr><br><br>
  {% else %}
    <h1 class="empty-cart">У вас немає товарів у кошику</h1>
  {% endif %}
{% endblock %}
{% block js-files %} 
<script src="{% static 'cart/js/cart.js' %}" crossorigin="anonymous"></script> 
{% endblock %}