cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls'), name='orders'),
    path('cart/', include('cart.urls'), name='cart'),
    path('', include('shop.urls'), name='shop'),
]


if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home.as_view(), name='product_list'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('<slug:category_slug>/', views.ProductList.as_view(), name='product_list_by_category'),
    path('product/<slug:product_slug>/', views.ProductDetail.as_view(), name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Назва категорії')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='URL')

    class Meta:
        ordering = ('name',)
        verbose_name = 'категорію'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category',
                        args=[self.slug])


class Brend(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Назва категорії')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='URL')

    class Meta:
        ordering = ('name',)
        verbose_name = 'виробника'
        verbose_name_plural = 'виробники'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.PROTECT,
                                 verbose_name='Категорія товару')
    brend = models.ForeignKey(Brend, related_name='products', on_delete=models.PROTECT, verbose_name='бренд товару')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Назва товару')
    main_image = models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Основне зображення товару')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='URL')
    description = models.TextField(blank=True, verbose_name='Опис товару')
    old_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True,
                                    verbose_name='Ціна до знижки')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна товару')
    stock = models.PositiveIntegerField(verbose_name='Залишок товару')
    available = models.BooleanField(default=True, verbose_name='Доступність товару на складі')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'товар'
        verbose_name_plural = 'Товари'
        ordering = ['-updated', '-created', '-id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail',
                        args=[self.slug])


class Characteristic(models.Model):
    product = models.ForeignKey('Product', related_name='characteristic_items', on_delete=models.PROTECT)
    name = models.CharField(max_length=200, db_index=True, verbose_name='назва характеристики')
    value = models.CharField(max_length=200, db_index=True, verbose_name='Значення характиристики')

    class Meta:
        verbose_name = 'характеристику'
        verbose_name_plural = 'характеристики'

    def __str__(self):
        return self.name


class ProductImages(models.Model):
    product = models.ForeignKey('Product', related_name='product_image', on_delete=models.PROTECT)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Зображення товару')


    class Meta:
        verbose_name = 'додаткове зображення товару'
        verbose_name_plural = 'Додаткові зображення товару'

    def __str__(self):
        return f'Зображення товару'

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'placeholder': 'Логін'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'placeholder': 'Eмеіл'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))
    password2 = forms.CharField(label='Повтор паролю',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Повтор паролю'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'placeholder': 'Логін'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

shop/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from .utils import *
from .forms import *
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy
from django.db.models import Q
from cart.forms import CartAddProductForm


class Home(DataMixin, ListView):
    model = Product
    template_name = 'shop/index.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Why Hub')
        return dict(list(context.items()) + list((c_def.items())))

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Product.objects.filter(Q(name__iregex=query), available=True).select_related('category')
        else:
            return Product.objects.filter(available=True).select_related('category')



class ProductList(DataMixin, ListView):
    model = Product
    template_name = 'shop/index.html'
    context_object_name = 'products'
    allow_empty = False

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'], available=True).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_image'] = ProductImages.objects.all()
        c = Category.objects.get(slug=self.kwargs['category_slug'])
        c_def = self.get_user_context(
            title='Категорія - ' + str(c.name),
            cat_selected=c.id)
        return dict(list(context.items()) + list((c_def.items())))


class ProductDetail(DataMixin, DetailView):
    model = Product
    slug_url_kwarg = 'product_slug'
    template_name = 'shop/detail.html'
    context_object_name = 'product'
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['characteristics'] = Characteristic.objects.all().filter(product_id=context['product'].id)
        context['product_image'] = ProductImages.objects.all().filter(product_id=context['product'].id)
        c_def = self.get_user_context(title = context['product'].name)
        return dict(list(context.items()) + list((c_def.items())))


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'shop/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title = 'Реєстрація')
        return dict(list(context.items()) + list((c_def.items())))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('product_list')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'shop/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title = 'Вхід')
        return dict(list(context.items()) + list((c_def.items())))

    def get_success_url(self):
        return reverse_lazy('product_list')


def logout_user(request):
    logout(request)
    return redirect('login')

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="uk-ua">
    <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      {% block css-files %}{% endblock %}
      <script src="https://kit.fontawesome.com/8abd8374d8.js" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="{% static 'shop/css/default.css' %}" />
      <link rel="stylesheet" href="{% static 'shop/css/header.css' %}" />
      <link rel="stylesheet" href="{% static 'shop/css/main.css' %}" />
      <link rel="stylesheet" href="{% static 'shop/css/footer.css' %}" />
      <title>{% block title %}{% endblock %}</title>
    </head>
  <body>
    <div class="page-wrapper">
      <header class="header">
        <div class="container">
          <div class="logo-wrapper">
            <a href="{% url 'product_list' %}" class="nav-link"><img class="logo-img" src="{% static 'shop/img/logo.png' %}" alt=""></a>
          </div>
          <div class="search-wrapper">
            <form action="{% url 'product_list' %}" method="get">
              <input name="q" class="search-input" type="input" placeholder="Пошук...">
              <button class="search-buttton">Знайти</button>
            </form>
          </div>
          <div class="nav-list-wrapper">
            <nav>
              <ul>
                {% if request.user.is_authenticated %}
                <li class="nav-list-item">
                  <a href="{% url 'cart:cart_detail' %}" class="nav-link">
                    <i class="fa-regular fa-heart fa-lg"></i>
                  </a>
                </li>
                <li class="nav-list-item">
                  <a href="{% url 'cart:cart_detail' %}" class="nav-link">
                    <i class="fa-solid fa-cart-shopping fa-lg"></i>
                  </a>
                </li>
                <li class="nav-list-item">
                  {{ user.username }} | <a href="{% url 'logout' %}" class="nav-link">Вийти</a>
                </li>
                {% else %}
                <li class="nav-list-item">
                  <a href="{% url 'cart:cart_detail' %}" class="nav-link">
                    <i class="fa-regular fa-user fa-lg"></i>
                  </a>
                </li>
                <li class="nav-list-item">
                  <a href="{% url 'cart:cart_detail' %}" class="nav-link">
                    <i class="fa-regular fa-heart fa-lg"></i>
                  </a>
                </li>
                <li class="nav-list-item">
                  <a href="{% url 'cart:cart_detail' %}" class="nav-link">
                    <i class="fa-solid fa-cart-shopping fa-lg"></i>
                  </a>
                </li>
                <li class="nav-list-item">
                  <a href="{% url 'login' %}" class="nav-link">Увійти</a> | <a href="{% url 'register' %}" class="nav-link">Реєстрація</a>
                </li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
        <div class="korable">
          <p><i class="fa-solid fa-ship"> РУСКИЙ ВОЄНИЙ КОРАБЛЬ ІДИ НА*УЙ !</i></p>
        </div>
      </header>
      <main>
        {% block content %}
        {% endblock %}
          {% if page_obj.has_other_pages %}
          <nav class="list-pages">
            <ul>
              {% if page_obj.has_previous %}
                <li class="page-number">
                  <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                </li>
              {% endif %}
              {% for p in paginator.page_range %}
                {% if page_obj.number ==  p %}
                  <li class="page-number page-number-selected">
                    <a href="?page={{ p }}">{{ p }}</a>
                  </li>
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                  <li class="page-number">
                    <a href="?page={{ p }}">{{ p }}</a>
                  </li>
                {% endif %} 
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-number">
                  <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
                </li>
              {% endif %}
            </ul>
          </nav>
        {% endif %}
        <a id="upbutton" href="#" onclick="smoothJumpUp(); return false;">
          <i class="fas fa-chevron-up fa-2xl"></i>
        </a>
      </main>
      <footer class="footer-site">
        <div class="container">
          <div class="logo-wrapper">
            <a href="{% url 'product_list' %}" class="nav-link"><img class="logo-img" src="{% static 'shop/img/logo.png' %}" alt=""></a>
            <div class="infofooter">
            <p>Наші Контакти</p>
            <p>067-339-4527</p>
            </div>
          </div>
          <div>
            <p  class="social">Ми в соц.мережах</p><br>
            <ul class="widget-social">
              <li>
                <a href="" i class="fa-brands fa-instagram fa-2xl"></i></a>
              </li>
              <li>
                <a href="" i class="fa-brands fa-facebook fa-2xl"></i></a>
              </li>
              <li>
                <a href="" i class="fa-brands fa-twitter fa-2xl"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
      {% block js-filles %}{% endblock %}
      <script type="text/javascript" src="{% static 'shop/js/jquery.js' %}"></script>
    </div>
  </body>
</html>

shop/templates/shop/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css-files %} 
    <link rel="stylesheet" href="{% static 'shop/css/about-goods.css' %}" />
    <link rel="stylesheet" href="{% static 'shop/css/slider.css' %}" />
{% endblock %}

{% block title %}
    {{ title }}
{% endblock %}


{% block content %}
    

<div class="container">
    <div class="left-columb">
        <div class="slider-container">
            <div class="some-block">
                <button class="Right"><i class="fa-solid fa-chevron-left fa-2xl"></i></button>
            </div>
            <div class="slider">     
                <img class="slide-img" src="{% if product.main_image %}{{ product.main_image.url }}{% endif %}" alt="">       
                {% for el in product_image %}                  
                    <img class="slide-img" src="{% if el.image %}{{ el.image.url }}{% endif %}" alt="">
                {% endfor %}
            </div>
            <div class="some-block">
                <button class="Left"><i class="fa-solid fa-chevron-right fa-2xl"></i></button>
            </div>
        </div>
        <div class="similar-products">
            <p>Схожі товари</p>
        </div>
        <div class="box">
            <div class="box1">
                <a href="{{ product.category.get_absolute_url }}">
                    <img src="{% static 'shop/img/logo.png' %}">
                </a>
                <p>INTEL CORE i5 10TH GEN</p>
            </div>
            <div class="box1">
                <a href="{{ product.category.get_absolute_url }}">
                    <img src="{% static 'shop/img/logo.png' %}">
                </a>
                <p>INTEL CORE i5 10TH GEN</p>
            </div>
            <div class="box1">
                <a href="{{ product.category.get_absolute_url }}">
                    <img src="{% static 'shop/img/logo.png' %}">
                </a>
                <p>INTEL CORE i5 10TH GEN</p>
            </div>
            <div class="box1">
                <a href="{{ product.category.get_absolute_url }}">
                    <img src="{% static 'shop/img/logo.png' %}">
                </a>
                <p>INTEL CORE i5 10TH GEN</p>
            </div>
        </div>
    </div>
    <div class="right-columb"><!-- Product Description -->
        <div class="description">
            <h1>{{ product.name }}</h1>
            <div class="product-price">
                <p>{{ product.price }} ₴</p>
                <form action="{% url "cart:cart_add" product.pk %}" method="post">
                    <div class="quantity-wrapper">
                        <div class="quantity">
                            {{ cart_product_form.quantity }}
                        </div>
                    </div>
                    {% csrf_token %}
                    <button type="submit" class="cart-btn">Купити</button>
                </form>
            </div>
            <input type="checkbox" class="read-more-checker" id="read-more-checker" />
            <div class="limited l-200">
                <p class="product-description">{{ product.description}}</p>
            <div class="bottom"></div>
            </div>
            <label for="read-more-checker" class="read-more-button"></label>
        </div>
        <p class="xarakteristick-label">Характеристики</p>
        <div class="product-characteristics">
            {% for c in characteristics %}
                <div class="product-characteristics-row">
                    <div class="product-characteristics-item"><p>{{ c.name }}</p></div>
                    <div class="product-characteristics-item"><p>{{ c.value }}</p></div>
                </div>
            {% endfor %}
        </div>
    </div>
</div
{% endblock %}
{% block js-filles %}
    <script type="text/javascript" src="{% static 'shop/js/script.js' %}"></script>
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load shop_tags %}
{% load static %}

  
{% block title %} 
  {{ title }}
{% endblock %}

  {% block content %}
    {% get_cats as categories %}
    <div class="container">
      {% show_categories cat_selected=cat_selected %}
      <div class="products-table">
        {% if products %} 
        {% for el in products %}
          <div class="card">
            <div class="product-card">
              {% if el.old_price %}<div class="badge">Знижка!</div> {% endif %}
              <div class="product-tumb">
                {% if el.main_image %}
                  <a href="{{ el.get_absolute_url }}">
                    <img src="{{ el.main_image.url }}" class="product-card-image" alt="">
                  </a>
                {% endif %}
              </div>
              <div class="product-details">
                <span class="product-catagory">{{ el.category }}</span>
                <h4><a href="{{ el.get_absolute_url }}">{{ el.name }}</a></h4>
                <p>{{ el.description }}</p>
                <div class="product-bottom-details">
                  <div class="product-price">{{ el.price }}₴</div>
                  <div class="product-links">
                    <form action="{% url "cart:cart_add" el.pk %}" method="post">
                      <p style="display: none;">{{ cart_product_form.quantity }}</p>
                      {{ cart_product_form.update }}
                      {% csrf_token %}
                      <button type="submit" class="submit-button"><a href=""><i class="fa fa-shopping-cart"></i></a></button>
                      <a href=""><i class="fa fa-heart"></i></a>
                  </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        {% else %}
          <p>У нас немає товарів</p>
        {% endif %}
      </div>
    </div>
{% endblock %}

shop/templates/shop/list_categories.html
<div class="products-nav">
    <ul>
      <li {% if cat_selected %}class="product-nav-link"{% else %} class="product-selected-link" {% endif %}>
            <a href="{% url "product_list" %}">Усі категорії</a></li>
        {% for c in cats %}
        <li {% if cat_selected == c.id %} class="product-selected-link" {% else %} class="product-nav-link" {% endif %}>
            <a class="product-hover" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
</div>

shop/templates/shop/login.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css-files %} 
    <link rel="stylesheet" href="{% static 'shop/css/login.css' %}" />
{% endblock %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="authentication-form">
        <form method="post">
            {% for f in form %}
            <div class="authentication-form-item">
                {{ f }}
                <div class="form-error">
                    {{ f.errors }}
                </div>
            </div>
            {% csrf_token %}
            {% endfor %}
            <button class="authentication-button" type="submit">Увійти</button>
        </form>
    </div>
</div>
{% endblock %}

shop/templates/shop/register.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css-files %} 
    <link rel="stylesheet" href="{% static 'shop/css/login.css' %}" />
{% endblock %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="authentication-form">
        <form method="post">
            {% for f in form %}
            <div class="authentication-form-item">
                {{ f }}
                <div class="form-error">
                    {{ f.errors }}
                </div>
            </div>
            {% csrf_token %}
            {% endfor %}
            <button class="authentication-button" type="submit">Зареєструватися</button>
        </form>
    </div>
</div>
{% endblock  %}